CREATE DATABASE IF NOT EXISTS api_educativa_db;
USE api_educativa_db;

CREATE TABLE IF NOT EXISTS pessoas (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100), idade INT, cpf VARCHAR(20), cidade VARCHAR(100), criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS carros (id INT AUTO_INCREMENT PRIMARY KEY, marca VARCHAR(100), modelo VARCHAR(100), ano INT, cor VARCHAR(50), criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS casas (id INT AUTO_INCREMENT PRIMARY KEY, endereco VARCHAR(255), bairro VARCHAR(100), valor DECIMAL(10,2), vagas INT, criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cachorros (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100), raca VARCHAR(100), idade INT, dono VARCHAR(100), criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);